name: patch_pal
description: Flutter package thats helps you to patch your widget/code with json data.
version: 0.0.2
homepage: https://github.com/yeasin50/patch_pal

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  mockito: ^5.4.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter:
 
